name: Publish (Dry)
'on':
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: canary

      - name: Format
        id: format
        run: |
          trap 'echo "exit-code=$?" >> "$GITHUB_OUTPUT"' EXIT
          deno fmt --check
      - name: Commit formatted code
        run: |
          deno fmt
          git config --local user.name "deno fmt"
          git add .
          git commit -m "Formatted your code for you!"
          git push
        if: ${{ steps.format.outputs.exit-code }} != 0
      - name: Publish to JSR (dry)
        run: deno publish --dry-run
        if: ${{ steps.format.outputs.exit-code }} == 0