name: Publish (Dry)
'on':
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: canary

      - name: Format dry
        id: format
        run: |
          deno fmt --check
          echo "::set-output name=exit-code::$?"
        continue-on-error: true

      - name: Format (if dry format failed)
        run: deno fmt
        if: ${{ steps.format.outputs.exit-code }} != 0

      - name: Commit
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /user
          git config --global user.name 'deno fmt' 
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add .
          git commit -am "Format code"
          git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.format.outputs.exit-code }} != 0
  
      - name: Publish to JSR (dry)
        run: deno publish --dry-run
        if: ${{ steps.format.outputs.exit-code }} == 0